name: 'Fix cloud issues in IaC Pipeline'

on:
  push:
    branches:
    - main

jobs:
  deployment-job: 
    name: 'Deployment Pipeline' 
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

## Terraform init, state pull
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.1.7
        terraform_wrapper: false

    - name: Terraform init
      run: terraform init

    # - name: Terraform Apply
    #   run: terraform apply --auto-approve 
    #   continue-on-error: true

    # - name: Terraform state pull and Capture
    #   run: terraform state pull | snyk iac capture --stdin

## Send report to Snyk UI
    - name: Run Snyk Report
      run : |
           curl -sSL -o /usr/local/bin/snyk https://static.snyk.io/cli/latest/snyk-linux
           chmod +x /usr/local/bin/snyk
           snyk iac test --report --org=${{ secrets.SNYK_ORG }} 
      continue-on-error: true

### Trigger Scan of the environment
    - name: Trigger a scan
      shell: bash
      run: ./scripts/cloudscan.sh

